apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels: 
    name: karpenter
    env: non-prod
  annotations: 
    description: "Karpenter is an node provisioning project built for Kubernetes. It automatically launches just the right compute resources to handle your cluster's applications."
